service: nestjs-lamnda-example

plugins:
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x

functions:
  main:
    handler: dist/main.handler
    environment:
      ENVIRONMENT: development
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
